name: "Hello Actions"
description: "Greet someone"
author: "juan.posada@hunty.com"

input:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "World"
    
runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"
